CREATE MATERIALIZED VIEW IF NOT EXISTS dwh.customers_parsed_mv
TO dwh.customers_parsed AS
WITH parsed_data AS (
    SELECT
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.customer_id')), '') AS customer_id,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.first_name')), '') AS first_name,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.last_name')), '') AS last_name,
        nullIf(JSON_VALUE(full_data, '$.email'), '') AS email,
        nullIf(JSON_VALUE(full_data, '$.phone'), '') AS phone,
        toDateOrNull(JSON_VALUE(full_data, '$.birth_date')) AS birth_date,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.gender')), '') AS gender,
        toDateTime64OrNull(JSON_VALUE(full_data, '$.registration_date'), 6) AS registration_date,
        JSONExtractBool(full_data, 'is_loyalty_member') AS is_loyalty_member,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.loyalty_card_number')), '') AS loyalty_card_number,

        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.country')), '') AS purchase_country,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.city')), '') AS purchase_city,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.street')), '') AS purchase_street,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.house')), '') AS purchase_house,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.postal_code')), '') AS purchase_postal_code,
        toFloat64OrNull(JSON_VALUE(full_data, '$.purchase_location.coordinates.latitude')) AS purchase_latitude,
        toFloat64OrNull(JSON_VALUE(full_data, '$.purchase_location.coordinates.longitude')) AS purchase_longitude,

        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.country')), '') AS delivery_country,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.city')), '') AS delivery_city,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.street')), '') AS delivery_street,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.house')), '') AS delivery_house,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.apartment')), '') AS delivery_apartment,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.postal_code')), '') AS delivery_postal_code,

        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.preferences.preferred_language')), '') AS preferred_language,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.preferences.preferred_payment_method')), '') AS preferred_payment_method,
        JSONExtractBool(full_data, 'preferences.receive_promotions') AS receive_promotions,

        cityHash64(
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.customer_id')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.first_name')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.last_name')), ''),
            nullIf(JSON_VALUE(full_data, '$.email'), ''),
            nullIf(JSON_VALUE(full_data, '$.phone'), ''),
            toDateOrNull(JSON_VALUE(full_data, '$.birth_date')),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.gender')), ''),
            toDateTime64OrNull(JSON_VALUE(full_data, '$.registration_date'), 6),
            JSONExtractBool(full_data, 'is_loyalty_member'),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.loyalty_card_number')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.country')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.city')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.street')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.house')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.purchase_location.postal_code')), ''),
            toFloat64OrNull(JSON_VALUE(full_data, '$.purchase_location.coordinates.latitude')),
            toFloat64OrNull(JSON_VALUE(full_data, '$.purchase_location.coordinates.longitude')),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.country')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.city')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.street')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.house')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.apartment')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.delivery_address.postal_code')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.preferences.preferred_language')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.preferences.preferred_payment_method')), ''),
            JSONExtractBool(full_data, 'preferences.receive_promotions')
        ) AS row_hash
    FROM default.customers_data
    WHERE isValidJSON(full_data) AND full_data != ''
)
SELECT DISTINCT
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    birth_date,
    gender,
    registration_date,
    is_loyalty_member,
    loyalty_card_number,
    purchase_country,
    purchase_city,
    purchase_street,
    purchase_house,
    purchase_postal_code,
    purchase_latitude,
    purchase_longitude,
    delivery_country,
    delivery_city,
    delivery_street,
    delivery_house,
    delivery_apartment,
    delivery_postal_code,
    preferred_language,
    preferred_payment_method,
    receive_promotions,
    row_hash
FROM parsed_data
LEFT ANTI JOIN dwh.customers_parsed ON parsed_data.row_hash = dwh.customers_parsed.row_hash;
