CREATE MATERIALIZED VIEW IF NOT EXISTS dwh.stores_parsed_mv
TO dwh.stores_parsed AS
WITH parsed_data AS (
    SELECT
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$._id')), '') AS id,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.store_id')), '') AS store_id,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.store_name')), '') AS store_name,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.store_network')), '') AS store_network,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.store_type_description')), '') AS store_type_description,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.type')), '') AS type,
        JSONExtract(full_data, 'categories', 'Array(String)') AS categories,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.manager.name')), '') AS manager_name,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.manager.phone')), '') AS manager_phone,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.manager.email')), '') AS manager_email,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.country')), '') AS country,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.city')), '') AS city,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.street')), '') AS street,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.house')), '') AS house,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.postal_code')), '') AS postal_code,
        toFloat64OrNull(JSON_VALUE(full_data, '$.location.coordinates.latitude')) AS latitude,
        toFloat64OrNull(JSON_VALUE(full_data, '$.location.coordinates.longitude')) AS longitude,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.opening_hours.mon_fri')), '') AS opening_mon_fri,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.opening_hours.sat')), '') AS opening_sat,
        nullIf(lowerUTF8(JSON_VALUE(full_data, '$.opening_hours.sun')), '') AS opening_sun,
        JSONExtractBool(full_data, 'accepts_online_orders') AS accepts_online_orders,
        JSONExtractBool(full_data, 'delivery_available') AS delivery_available,
        JSONExtractBool(full_data, 'warehouse_connected') AS warehouse_connected,
        toDateOrNull(JSON_VALUE(full_data, '$.last_inventory_date')) AS last_inventory_date,

        cityHash64(
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$._id')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.store_id')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.store_name')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.store_network')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.store_type_description')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.type')), ''),
            JSONExtract(full_data, 'categories', 'Array(String)'),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.manager.name')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.manager.phone')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.manager.email')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.country')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.city')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.street')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.house')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.location.postal_code')), ''),
            toFloat64OrNull(JSON_VALUE(full_data, '$.location.coordinates.latitude')),
            toFloat64OrNull(JSON_VALUE(full_data, '$.location.coordinates.longitude')),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.opening_hours.mon_fri')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.opening_hours.sat')), ''),
            nullIf(lowerUTF8(JSON_VALUE(full_data, '$.opening_hours.sun')), ''),
            JSONExtractBool(full_data, 'accepts_online_orders'),
            JSONExtractBool(full_data, 'delivery_available'),
            JSONExtractBool(full_data, 'warehouse_connected'),
            toDateOrNull(JSON_VALUE(full_data, '$.last_inventory_date'))
        ) AS row_hash
    FROM default.stores_data
    WHERE isValidJSON(full_data) AND full_data != ''
)
SELECT DISTINCT
    id,
    store_id,
    store_name,
    store_network,
    store_type_description,
    type,
    categories,
    manager_name,
    manager_phone,
    manager_email,
    country,
    city,
    street,
    house,
    postal_code,
    latitude,
    longitude,
    opening_mon_fri,
    opening_sat,
    opening_sun,
    accepts_online_orders,
    delivery_available,
    warehouse_connected,
    last_inventory_date,
    row_hash
FROM parsed_data
LEFT ANTI JOIN dwh.stores_parsed ON parsed_data.row_hash = dwh.stores_parsed.row_hash;