apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: click-1
    access: proxy
    url: http://clickhouse:9000
    database: default
    isDefault: true
    jsonData:
      defaultDatabase: default
      server: clickhouse
      port: 9000
      username: user
      secure: false
    secureJsonData:
      password: "strongpassword"
    editable: true
