version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    ports:
      - "${ZOOKEEPER_PORT:-2181}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    container_name: zookeeper-server

  kafka:
    image: confluentinc/cp-kafka:7.3.3
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:${KAFKA_PORT:-9092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    container_name: kafka-server

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "${KAFKA_UI_PORT:-8082}:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      
      KAFKA_CLUSTERS_0_NAME: "Local Kafka Cluster - STEPIK_DE"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

      KAFKA_CLUSTERS_0_METRICS_CONFIG_TYPE: JMX
      KAFKA_CLUSTERS_0_METRICS_CONFIG_PORT: 9997
      KAFKA_CLUSTERS_0_METRICS_CONFIG_HOST: kafka
    
    depends_on:
      - kafka
      - zookeeper
    restart: unless-stopped

  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DATABASE:-test_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: postgres-server

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: always
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
      - "${CLICKHOUSE_PORT:-9000}:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144            
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-user}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-strongpassword}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse    

volumes:
  pgdata:
  clickhouse_data: